HMS.MVC/Models/AffiliatedWithViewModel.cs
using HMS.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HMS.MVC.Models
{
    public class AffiliatedWithViewModel
    {
        public int PhysicianId { get; set; }
        
        public int DepartmentId { get; set; }

        public bool PrimaryAffiliation { get; set; }

        public Department Department { get; set; }

        public Physician Physician { get; set; }
        public string PhysicianName { get; internal set; }
        public string DepartmentName { get; internal set; }
    }
}

HMS.MVC/Controllers/AffiliatedWithController.cs
using Newtonsoft.Json;
using HMS.Service.AffiliatedWithService;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HMS.Core;
using HMS.MVC.Models;
using System.Collections;
using System.Collections.Generic;
using Syncfusion.EJ2.Base;
using AutoMapper;
using System.Web.Http;

namespace HMS.Web.Controllers
{
    public class AffiliatedWithController : Controller
    {
        private readonly IAffiliatedWithService _repository;

        public AffiliatedWithController(IAffiliatedWithService repository)
        {
            _repository = repository;
        }
        const string ValidationErrorMessage = "The record cannot be saved due to a validation error";

        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult Get(DataManagerRequest dm)
        {
            var DataSource = _repository.GetAffiliatedWiths()
                .Select(x => new AffiliatedWithViewModel
                {
                    PhysicianId = x.Physician,
                    PhysicianName = x.Physician1.Name,
                    DepartmentName = x.Department1.Name,
                    DepartmentId = x.Department,
                    PrimaryAffiliation = x.PrimaryAffiliation

                });

            DataOperations operation = new DataOperations();
            List<string> str = new List<string>();
            if (dm.Search != null && dm.Search.Count > 0)
            {
                DataSource = operation.PerformSearching(DataSource, dm.Search);  //Search
            }
            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                DataSource = operation.PerformSorting(DataSource, dm.Sorted);
            }
            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                DataSource = operation.PerformFiltering(DataSource, dm.Where, dm.Where[0].Operator);
            }
            int count = DataSource.Cast<AffiliatedWithViewModel>().Count();
            if (dm.Skip != 0)
            {
                DataSource = operation.PerformSkip(DataSource, dm.Skip);         //Paging
            }
            if (dm.Take != 0)
            {
                DataSource = operation.PerformTake(DataSource, dm.Take);
            }

            ViewBag.physician = DataSource;
            return dm.RequiresCounts ? Json(new { result = DataSource, count = count }) : Json(DataSource);

        }

        
        public ActionResult Insert(AffiliatedWithViewModel value)
        {
            var result = new Affiliated_With
            {
                Physician = value.PhysicianId,
                Department = value.DepartmentId,
                PrimaryAffiliation = value.PrimaryAffiliation
            };

            _repository.InsertAffiliatedWith(result);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult Update(AffiliatedWithViewModel value)
        {
            var result = new Affiliated_With
            {
                Physician = value.PhysicianId,
                Physician1 = value.Physician,
                Department = value.DepartmentId,  
                Department1 = value.Department,
                PrimaryAffiliation = value.PrimaryAffiliation
            };

            _repository.UpdateAffiliatedWith(result);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult Delete(int key)
        {
            _repository.DeleteAffiliatedWith(key);
            return new EmptyResult();
        }
        
    }
    public class EditParams
    {
        //Paging Params
        public int skip { get; set; }
        public int take { get; set; }

        //Grid Action Params
        public string action { get; set; }
        public int key { get; set; }
        public string keyColumn { get; set; }
        public Affiliated_With value { get; set; }

        //Batch Edit Params
        public IEnumerable<Affiliated_With> added { get; set; }
        public IEnumerable<Affiliated_With> changed { get; set; }
        public IEnumerable<Affiliated_With> deleted { get; set; }
    }

}

HMS.MVC/Controllers/DashboardsController.cs
using HMS.Core;
using HMS.Infrastructure.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HMS.Web.Controllers
{
    public class DashboardsController : Controller
    {
        private readonly IRepository<Appointment> _repository;

        public DashboardsController(IRepository<Appointment> repository)
        {
            _repository = repository;
        }

        public ActionResult Dashboard_1()
        {
            return View();
        }

        public ActionResult Dashboard_2()
        {
            //ChartData(_repository.GetAll.ToList());
            return View();
        }


        //public ActionResult ChartData(List<Appointment> d)
        //{
        //    //var appointments = d as Appointment[] ?? d.ToArray();
        //    var month = from item in d
        //                where item.EndDateDate.Year == DateTime.Today.Year
        //                orderby item.EndDateDate
        //                group item by new { month = item.EndDateDate.Month } into g                          
        //                select new
        //        {
        //            Month = g.Key.month,
        //            Count = g.Count()
        //        };
            

        //    ViewBag.ChartData =  month.Select(x => new int[]{x.Month, x.Count });
        //    return new JsonResult { Data = true, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        //}

        public ActionResult Dashboard_3()
        {
            return View();
        }
        
        public ActionResult Dashboard_4()
        {
            return View();
        }
        
        public ActionResult Dashboard_4_1()
        {
            return View();
        }

        public ActionResult Dashboard_5()
        {
            return View();
        }

    }
}

HMS.MVC/Views/AffiliatedWith/Index.cshtml
@{
    ViewBag.Title = "Affiliated With";
}



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Affiliated With</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Dashboard_2", "Dashboards")">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "AffiliatedWith")">Affiliated With</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox box-s@usinghadow float-e-margins">
                <div class="ibox-content">
                    @Html.EJS().Grid("Grid").DataSource(dm => dm.Url(Url.Action("Get"))
                        .InsertUrl(Url.Action("Insert"))
                        .UpdateUrl(Url.Action("Update"))
                        .RemoveUrl(Url.Action("Delete"))
                        .Adaptor("UrlAdaptor")
                        
                        ).Columns(col =>
                        {
                            col.Field("PhysicianName").IsPrimaryKey(true).ForeignKeyValue("PhysicianName").ForeignKeyField("PhysicianName").DataSource((IEnumerable<object>)ViewBag.physician).EditType("dropdownedit").HeaderText("Physician").Width("120").ValidationRules(new { required = true }).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                            col.Field("DepartmentName").IsPrimaryKey(true).ForeignKeyValue("DepartmentName").ForeignKeyField("DepartmentName").DataSource((IEnumerable<object>)ViewBag.physician).EditType("dropdownedit").HeaderText("Department").Width("150").ValidationRules(new { required = true }).Add();
                            col.Field("PrimaryAffiliation").HeaderText("Primary Affiliation").EditType("booleanedit").DisplayAsCheckBox(true).Type("boolean").Width("130").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                        }).AllowPaging().AllowExcelExport(true).AllowFiltering().EditSettings(edit =>
                                    edit.AllowAdding(true).AllowEditing(true)
                                    .AllowDeleting(true).Mode(Syncfusion.EJ2.Grids.EditMode.Normal)).Toolbar(new List<string>()
                                    { "Add", "Edit", "Delete", "Update", "Cancel" ,"Search" }).Render()



</div>
            </div>
        </div>
    </div>
</div>

@*<script type="text/javascript">
    var data = @Html.Raw(Json.Encode(ViewBag.DataSource))
        function create() {
            return $("<input>");
        }
    function Write(args) {
        args.element.ejComboBox({
            dataSource: ej.dataUtil.distinct(data, "PhysicianName", true),
            fields: { text: "Physician Name" },
            placeholder: 'Select a Physician',
            value: args.rowdata["PhysicianName"]
        });
    }

    function read(args) {
        var ID = $(".e-combobox").closest(".e-grid").attr("id")
        return $("#" + ID + "PhysicianName").val();
    }

    function bound(args) {
        this.element.width(500)
    }
</script>*@