HMS.Web/Controllers/ProceduresController.cs
using HMS.Core;
using Newtonsoft.Json;
using Service.ProcedureService;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ProceduresController : Controller
    {
        private readonly IProcedureService _repository;

        public ProceduresController(IProcedureService repository)
        {
            _repository = repository;
        }
        const string ValidationErrorMessage = "The record cannot be saved due to a validation error";

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Get()
        {
            loadOptions.PrimaryKey = new[] { "Code" };

            var proceduresQuery = from p in _repository.GetProcedures()
                                  select new
                                  {
                                      p.Code,
                                      p.Name,
                                      p.Cost
                                  };

            var loadResult = DataSourceLoader.Load(proceduresQuery, loadOptions);
            return Content(JsonConvert.SerializeObject(loadResult), "application/json");
        }

        [HttpPut]
        public ActionResult Put(string key, string values)
        {

            var keyObj = JsonConvert.DeserializeObject<CompositeKey>(key);
            var procedure = _repository.Find(keyObj.Physician, keyObj.Patient, keyObj.Medication, keyObj.Date);
            JsonConvert.PopulateObject(values, procedure);

            if (!TryValidateModel(procedure))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ValidationErrorMessage);
            }
            _repository.UpdateProcedure(procedure);
            return new EmptyResult();
        }

        [HttpPost]
        public ActionResult Post(string values)
        {
            var procedure = new Procedure();
            JsonConvert.PopulateObject(values, procedure);

            if (!TryValidateModel(procedure))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ValidationErrorMessage);
            }

            _repository.InsertProcedure(procedure);

            return new EmptyResult();
        }

        [HttpDelete]
        public ActionResult Delete(int key)
        {
            _repository.DeleteProcedure(key);

            return new EmptyResult();
        }
    }
}

HMS.Web/Views/Procedures/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Index</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Dashboard_2", "Dashboards")">Home</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="@Url.Action("Index", "Procedures")">Procedures</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox box-shadow float-e-margins">
                <div class="ibox-content">

                    @(Html.DevExtreme().DataGrid<Procedure>()
                                                .DataSource(ds => ds.Mvc()
                                                    .Controller("Procedures")
                                                    .LoadAction("Get")
                                                    .UpdateAction("Put")
                                                    .InsertAction("Post")
                                                    .Key("Code"))
                                                    .ShowColumnLines(true)
                                                    .ShowRowLines(false)
                                                    .RowAlternationEnabled(true)
                                                    .ShowBorders(true)
                                                 .ShowBorders(true)
                                                .ShowBorders(true)
                                                .Paging(p => p.Enabled(true))
                                                .Editing(e => e.Mode(GridEditMode.Popup)
                                                .AllowAdding(true)
                                                .AllowDeleting(true)
                                                .AllowUpdating(true)

                                                .Popup(p => p
                                                    .Title("Block Info")
                                                    .ShowTitle(true)
                                                    .Width(700)
                                                            .Height(350)
                                                    .Position(pos => pos
                                                            .My(HorizontalAlignment.Center, VerticalAlignment.Top)
                                                            .At(HorizontalAlignment.Center, VerticalAlignment.Top)
                                                            .Of(new JS("window"))
                                                        )
                                                        )
                                                    )


                                                    .RemoteOperations(true)
                                                    .Columns(columns =>
                                                    {
                                                        columns.AddFor(m => m.Code);
                                                        columns.AddFor(m => m.Name);
                                                        columns.AddFor(m => m.Cost);

                                                    })
                                                            .Paging(p => p.PageSize(10))
                                                            .FilterRow(f => f.Visible(true))
                                                            .HeaderFilter(f => f.Visible(true))
                                                            .GroupPanel(p => p.Visible(true))
                                                            .Grouping(g => g.AutoExpandAll(false))
                                                            .RemoteOperations(true)
                                                            .Pager(p => p
                                                                                .ShowPageSizeSelector(true)
                                                                                .AllowedPageSizes(new int[] { 5, 10, 20, })
                                                                            )
                                                            .Summary(s => s
                                                                .TotalItems(totalItems =>
                                                                {
                                                                    totalItems.AddFor(m => m.Code).SummaryType(SummaryType.Count);
                                                                })
                                                                .GroupItems(groupItems =>
                                                                {
                                                                    groupItems.Add().SummaryType(SummaryType.Count);
                                                                })
                                                            )
                    )

                </div>
            </div>
        </div>
    </div>
</div>